// <auto-generated />
using BlogPostCMS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlogPostCMS.Migrations
{
    [DbContext(typeof(BlogDbContext))]
    partial class BlogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BlogPostCMS.Models.Post", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("Title");

                    b.HasKey("ID");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "Cats are the best!",
                            Title = "Cats Rule"
                        },
                        new
                        {
                            ID = 2,
                            Description = "It's true, the internet said so",
                            Title = "Coffee drinkers live longer lives"
                        },
                        new
                        {
                            ID = 3,
                            Description = "We all have fun learning. Make our brains exercise!!",
                            Title = "Learning is Fun!"
                        },
                        new
                        {
                            ID = 4,
                            Description = "Disney Addiction is a real thing. We all love Mickey! He is the happiest mouse on earth!",
                            Title = "Disney Addictions"
                        },
                        new
                        {
                            ID = 5,
                            Description = "Cohort 6 is the best cohort of 2019!",
                            Title = "Code Fellows .NET Cohort 6"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
